[project]
name = "mitra-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "firebase-admin>=6.5.0",
    "google-genai>=1.32.0",
    "pillow>=11.3.0",
    "uvicorn>=0.35.0",
]
